name: Build and Publish nuget package
on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ENV1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: nuget pack TSwiftIoC/TSwiftIoC.nuspec -OutputDirectory ./nupkg

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_NUGET_PUBL_TOKEN }}
      run: nuget push ./nupkg/*.nupkg -ApiKey $GITHUB_TOKEN --source https://nuget.pkg.github.com/tigyijanos/index.json

    - name: Publish to NuGet org
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: nuget push ./nupkg/*.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json 

    
      
