name: .NET NuGet Package
on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ENV1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: nuget pack TSwiftIoC/TSwiftIoC.nuspec -OutputDirectory ./nupkg

    - name: Publish to NuGet
      if: github.ref == 'refs/heads/main'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: nuget push ./nupkg/*.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json 
      
